label: "Uutisarkisto"
confirm_success_body: "Saat sähköpostiisi tiedon uusista osumista korkeintaan kerran päivässä.\nVoit perua tilauksen linkillä, jonka saat jokaisen ilmoituksen mukana.\nHakuvahti on voimassa kuusi kuukautta."
already_confirmed_body: "Saat sähköpostiisi tiedon uusista osumista korkeintaan kerran päivässä.\nVoit perua tilauksen linkillä, jonka saat jokaisen ilmoituksen mukana."
