external_links:
  jobs: 'https://www.hel.fi/fi/avoimet-tyopaikat'
  events: 'https://tapahtumat.hel.fi/fi'
  decisions: 'https://paatokset.hel.fi/fi'
  contact: 'https://www.hel.fi/fi/paatoksenteko-ja-hallinto/ota-yhteytta-helsingin-kaupunkiin'
ai_register_url: 'https://www.hel.fi/fi/'
