<?php

/**
 * @file
 * Contains alterations for the global navigation.
 */

declare(strict_types = 1);

use Drupal\system\MenuInterface;

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function helfi_global_navigation_menu_update(MenuInterface $entity) {
  if ($entity->id() === 'main') {
    // @todo figure out if there's a better way of determining the language.
    $lang_code = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $queue = \Drupal::queue('menu_queue');
    // Menu tree get built when queue executes, no need to hold old items.
    $queue->createQueue();
    $queue->createItem($lang_code);
  }

  return $entity;
}
