<?php

/**
 * @file
 * Contains alterations for the Hel.fi global navigation.
 */

declare(strict_types=1);

use Drupal\config_ignore\ConfigIgnoreConfig;
use Drupal\Core\Url;
use Drupal\helfi_api_base\Language\DefaultLanguageResolver;

/**
 * Implements hook_theme().
 */
function helfi_global_navigation_theme() : array {
  return [
    'debug_item' => [
      'variables' => [
        'data' => [],
      ],
      'template' => 'debug-item--helfi_globalmenu',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_global_navigation_preprocess_menu__external_menu(&$variables) : void {
  // Create current parent link for mobile menu.
  $variables['menu_link_current'] = [
    'title' => t('Front page'),
    'url' => Url::fromRoute('<front>'),
  ];

  // Construct urls for the menu items to help navigation via mobile menu.
  if (
    is_array($variables['items']) &&
    !empty($variables['items']) &&
    !array_key_exists('next_url', $variables['items'])
  ) {
    foreach ($variables['items'] as &$menu_link) {
      $menu_link['next_url'] = clone $menu_link['url'];
      $menu_link['next_url']->setOption('fragment', 'menu');
    }
  }
}

/**
 * Implements hook_config_ignore_ignored_alter().
 */
function helfi_global_navigation_config_ignore_ignored_alter(ConfigIgnoreConfig $ignored): void {
  $settings_to_ignore = [
    'block.block.external_header_top_navigation',
    'block.block.external_footer_top_navigation_2',
    'block.block.external_footer_top_navigation',
    'block.block.external_footer_bottom_navigation',
    'block.block.external_fallback_menu',
  ];

  // Add the menu blocks to the ignore list, but let the
  // external blocks to be deleted. Etusivu-instance
  // uses Drupal menus to render the block content.
  foreach (['create', 'update'] as $operation) {
    foreach (['import', 'export'] as $direction) {
      $list = array_merge(
        $ignored->getList($direction, $operation),
        $settings_to_ignore,
      );
      $ignored->setList($direction, $operation, $list);
    }
  }
}
