<?php

/**
 * @file
 * Hooks specific to the helfi_annif module.
 */

declare(strict_types=1);

/**
 * @addtogroup hooks
 * @{
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\helfi_annif\TextConverter\Document;

/**
 * Alter markup generated by RenderTextConverter.
 *
 * @param \Drupal\helfi_annif\TextConverter\Document $document
 *   The markup rendered using text_converter display.
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The original entity.
 *
 * @see \Drupal\helfi_annif\TextConverter\RenderTextConverter::convert()
 */
function hook_text_conversion_alter(Document $document, EntityInterface $entity) : void {
  $document->stripNodes("//*[contains(@class, 'visually-hidden')]");
}

/**
 * Alter markup generated by RenderTextConverter for specific entity types.
 *
 * @param \Drupal\helfi_annif\TextConverter\Document $document
 *   The markup rendered using text_converter display.
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The original entity.
 *
 * @see \Drupal\helfi_annif\TextConverter\RenderTextConverter::convert()
 */
function hook_entity_type_text_conversion_alter(Document $document, EntityInterface $entity) : void {
  assert($entity->getEntityTypeId(), 'entity_type');
}

/**
 * @} End of "addtogroup hooks".
 */
