<?php

/**
 * @file
 * Contains alterations for config.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\helfi_annif\TextConverter\Document;

/**
 * Implements hook_elasticsearch_connector_supported_data_types_alter().
 */
function helfi_annif_elasticsearch_connector_supported_data_types_alter(array &$data_types) {
  $data_types[] = 'ai_keyword';
}

/**
 * Implements hook_text_conversion_alter().
 */
function helfi_annif_text_conversion_alter(Document &$document, EntityInterface $entity) : void {
  // Strip nodes that are not displayed.
  $document
    ->stripNodes("//*[contains(@class, 'is-hidden')]")
    ->stripNodes("//*[contains(@class, 'visually-hidden')]");
}
