config_rewrite:
  replace: ['hidden', 'dependencies.module']
dependencies:
  module:
    - field_group
    - hdbt_admin_tools
    - linkit
    - media_library
    - paragraphs
    - path
    - publication_date
    - scheduler
    - select2
    - radioactivity
content:
  field_news_groups:
    type: select2_entity_reference
    weight: 26
    region: content
    settings:
      width: 100%
      autocomplete: false
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_news_neighbourhoods:
    type: select2_entity_reference
    weight: 27
    region: content
    settings:
      width: 100%
      autocomplete: false
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_radioactivity:
    type: radioactivity_reference
    weight: 28
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  hide_sidebar_navigation: true
