config_rewrite:
  replace: ['dependencies']
dependencies:
  config:
    - field.field.node.news_item.field_content
    - field.field.node.news_item.field_lead_in
    - field.field.node.news_item.field_main_image
    - field.field.node.news_item.field_main_image_caption
    - field.field.node.news_item.field_news_groups
    - field.field.node.news_item.field_news_item_links_link
    - field.field.node.news_item.field_news_item_links_title
    - field.field.node.news_item.field_news_item_tags
    - field.field.node.news_item.field_news_neighbourhoods
    - field.field.node.news_item.field_radioactivity
    - field.field.node.news_item.field_short_title
    - node.type.news_item
  module:
    - entity_reference_revisions
    - helfi_platform_config
    - link
    - radioactivity
    - user
content:
  field_news_groups:
    type: entity_reference_label
    label: above
    settings:
      link: false
    third_party_settings: {  }
    weight: 10
    region: content
  field_news_item_tags:
    type: entity_reference_label
    label: above
    settings:
      link: false
    third_party_settings: {  }
    weight: 11
    region: content
  field_news_neighbourhoods:
    type: entity_reference_label
    label: above
    settings:
      link: false
    third_party_settings: {  }
    weight: 12
    region: content
  field_news_item_updating_news:
    type: entity_reference_revisions_entity_view
    label: above
    settings:
      view_mode: default
      link: ''
    third_party_settings: {  }
    weight: 13
    region: content
  field_radioactivity:
    type: radioactivity_reference_emitter
    label: above
    settings:
      energy: 10.0
      display: false
      decimals: 0.0
    third_party_settings: {  }
    weight: 9
    region: content
hidden:
  langcode: true
  search_api_excerpt: true
  toc_enabled: true
