config_rewrite:
  replace: [
    'hidden',
    'dependencies',
    'third_party_settings.field_group.group_updating_news.children',
    'third_party_settings.field_group.group_automatically_recommended.children',
  ]
dependencies:
  config:
    - field.field.node.news_item.field_content
    - field.field.node.news_item.field_lead_in
    - field.field.node.news_item.field_main_image
    - field.field.node.news_item.field_main_image_caption
    - field.field.node.news_item.field_news_groups
    - field.field.node.news_item.field_news_item_links_link
    - field.field.node.news_item.field_news_item_links_title
    - field.field.node.news_item.field_news_item_tags
    - field.field.node.news_item.field_news_item_updating_news
    - field.field.node.news_item.field_news_neighbourhoods
    - field.field.node.news_item.field_radioactivity
    - field.field.node.news_item.field_short_title
    - node.type.news_item
  module:
    - field_group
    - hdbt_admin_tools
    - helfi_annif
    - linkit
    - media_library
    - paragraphs
    - path
    - publication_date
    - radioactivity
    - scheduler
    - select2
third_party_settings:
  field_group:
    group_updating_news:
      children:
        - field_news_item_updating_news
      label: 'Updating news'
      region: content
      parent_name: ''
      weight: 17
      format_type: details
      format_settings:
        classes: ''
        show_empty_fields: true
        id: ''
        open: false
        description: "Leave the content region above the updating news blank if you are creating an updating news.<br />\r\nAdd the latest news update at the end. The system will display updates on the page in reverse order."
        required_fields: false
    group_automatically_recommended:
      children:
        - in_recommendations
        - show_annif_block
        - annif_suggested_topics
      label: 'Automatically recommended content'
      region: content
      parent_name: ''
      weight: 28
      format_type: fieldset
      format_settings:
        classes: ''
        show_empty_fields: true
        id: ''
        description: 'Recommended content may include news or articles. Recommendations are based on automatically selected news categories. The news categories are chosen based on the page content when the page is saved.'
        required_fields: false
content:
  field_news_item_updating_news:
    type: paragraphs
    weight: 17
    region: content
    settings:
      title: Paragraph
      title_plural: Paragraphs
      edit_mode: open
      closed_mode: summary
      autocollapse: none
      closed_mode_threshold: 0
      add_mode: dropdown
      form_display_mode: default
      default_paragraph_type: _none
      features:
        add_above: '0'
        collapse_edit_all: '0'
        convert: '0'
        duplicate: '0'
    third_party_settings: {  }
  field_news_groups:
    type: select2_entity_reference
    weight: 25
    region: content
    settings:
      width: 100%
      autocomplete: false
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_news_item_tags:
    type: select2_entity_reference
    weight: 26
    region: content
    settings:
      width: 100%
      autocomplete: false
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_news_neighbourhoods:
    type: select2_entity_reference
    weight: 27
    region: content
    settings:
      width: 100%
      autocomplete: false
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_radioactivity:
    type: radioactivity_reference
    weight: 28
    region: content
    settings: {  }
    third_party_settings: {  }
  in_recommendations:
    type: boolean_checkbox
    weight: 0
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
  show_annif_block:
    type: boolean_checkbox
    weight: 1
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
  show_recommendations:
    type: boolean_checkbox
    weight: 0
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
hidden:
  hide_sidebar_navigation: true
