config_rewrite:
  replace: [
    'dependencies',
    'display.default.display_options.filters.langcode.value',
    'display.default.display_options.filter_groups.groups',
    'display.latest_news.display_options.filters.langcode.value',
    'display.latest_news.display_options.filter_groups.groups'
  ]
dependencies:
  config:
    - core.entity_view_mode.node.medium_teaser
    - core.entity_view_mode.node.tiny_teaser
    - field.storage.node.field_main_image
    - node.type.news_item
  module:
    - draggableviews
    - node
    - user
display:
  default:
    display_options:
      pager:
        options:
          items_per_page: 6
      sorts:
        weight:
          id: weight
          table: draggableviews_structure
          field: weight
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: draggable_views_sort_default
          order: ASC
          expose:
            label: ''
            field_identifier: ''
          exposed: false
          draggable_views_reference: this
          draggable_views_null_order: after
          draggable_views_pass_arguments: false
      filters:
        type:
          value:
            group: '1'
        promote:
          id: promote
          table: node_field_data
          field: promote
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          entity_field: promote
          plugin_id: boolean
          operator: '='
          value: '1'
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
        langcode:
          value:
            '***LANGUAGE_language_content***': '***LANGUAGE_language_content***'
      filter_groups:
        operator: AND
        groups:
          - AND
      row:
        options:
          view_mode: medium_teaser
  latest_news:
    display_options:
      title: 'Latest news'
      sorts:
        published_at:
          id: published_at
          table: node_field_data
          field: published_at
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          entity_field: published_at
          plugin_id: date
          order: DESC
          expose:
            label: ''
            field_identifier: ''
          exposed: false
          granularity: minute
      filters:
        status:
          id: status
          table: node_field_data
          field: status
          entity_type: node
          entity_field: status
          plugin_id: boolean
          value: '1'
          group: 1
          expose:
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
        type:
          id: type
          table: node_field_data
          field: type
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          entity_field: type
          plugin_id: bundle
          operator: in
          value:
            news_article: news_article
            news_item: news_item
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
        langcode:
          id: langcode
          table: node_field_data
          field: langcode
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          entity_field: langcode
          plugin_id: language
          operator: in
          value:
            '***LANGUAGE_language_interface***': '***LANGUAGE_language_interface***'
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
      filter_groups:
        operator: AND
        groups:
          - AND
      style:
        type: default
        options:
          row_class: ''
          default_row_class: true
          uses_fields: true
      row:
        type: 'entity:node'
        options:
          relationship: none
          view_mode: tiny_teaser
      defaults:
        title: false
        use_more: false
        use_more_always: false
        use_more_text: false
        link_display: false
        link_url: false
        style: false
        row: false
        sorts: false
        filters: false
        filter_groups: false
      use_more: true
      use_more_always: true
      use_more_text: 'See all news'
      link_display: custom_url
      link_url: /news
      display_extenders:
        metatag_display_extender: {  }
