display:
  default:
    display_options:
      filters:
        langcode:
          value:
            fi: fi
            sv: sv
            en: en
            de: de
            fr: fr
            ru: ru
            uk: uk
            ar: ar
            et: et
            fa: fa
            es: es
            so: so
            se: se
            zh-hans: zh-hans
