<?php

/**
 * @file
 * Contains hooks for 'helfi_node_news_article' module.
 */

declare(strict_types=1);

use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Access\AccessResultInterface;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\helfi_node_news_article\Entity\Node\NewsArticle;
use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function helfi_node_news_article_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['node']['news_article'])) {
    $bundles['node']['news_article']['class'] = NewsArticle::class;
  }
}

/**
 * Implements hook_themes_installed().
 */
function helfi_node_news_article_themes_installed($theme_list) {
  /** @var Drupal\helfi_platform_config\Helper\BlockInstaller $block_installer */
  $block_installer = Drupal::service('helfi_platform_config.helper.block_installer');

  foreach ($theme_list as $theme) {
    if (in_array($theme, ['stark', 'hdbt', 'hdbt_subtheme'])) {
      // Set the current theme as default theme.
      Drupal::configFactory()->getEditable('system.theme')
        ->set('default', $theme)
        ->save();

      foreach (helfi_node_news_article_get_block_configurations($theme) as $block_config) {
        ['block' => $block, 'variations' => $variations] = $block_config;
        $block_installer->install($block, $variations);
      }
    }
  }
}

/**
 * Gets the block configurations.
 *
 * Example block:
 *
 * @code
 * [
 *   'breadbrumbs' => [
 *     'block' => [
 *       ...
 *     ],
 *     'variations' => [
 *       ...
 *     ],
 *   ],
 * ];
 * @endcode
 *
 * @return array[]
 *   The block configurations.
 */
function helfi_node_news_article_get_block_configurations(string $theme) {
  return [
    'hdbt_subtheme_newsarticleheroblock' => [
      'block' => [
        'id' => 'hdbt_subtheme_newsarticleheroblock',
        'plugin' => 'news_article_hero_block',
        'provider' => 'helfi_node_news_article',
        'settings' => [
          'id' => 'news_article_hero_block',
          'label' => 'News article hero block',
          'label_display' => 0,
          'provider' => 'helfi_node_news_article',
        ],
        'visibility' => [
          'entity_bundle:node' => [
            'id' => 'entity_bundle:node',
            'negate' => FALSE,
            'context_mapping' => [
              'node' => '@node.node_route_context:node',
            ],
            'bundles' => [
              'news_article' => 'news_article',
            ],
          ],
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'before_content',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_node_news_article_helfi_paragraph_types() : array {
  $types = [
    'field_content' => [
      'text' => 0,
      'image' => 1,
      'remote_video' => 2,
      'banner' => 3,
    ],
  ];

  $enabled = [];
  foreach ($types as $field => $paragraphTypes) {
    foreach ($paragraphTypes as $paragraphType => $weight) {
      $enabled[] = new ParagraphTypeCollection('node', 'news_article', $field, $paragraphType, $weight);
    }
  }
  return $enabled;
}

/**
 * Implements hook_sidebar_visibility_allowed_entities().
 *
 * @see \hdbt_admin_tools_handle_sidebar_visibility
 */
function helfi_node_news_article_sidebar_visibility_allowed_entities_alter(array &$allowed_entities) : void {
  $allowed_entities['news_article'] = 'node';
}

/**
 * Implements hook_sidebar_visibility_alter().
 *
 * @see \hdbt_admin_tools_handle_sidebar_visibility
 */
function helfi_node_news_article_sidebar_visibility_alter(array &$variables, ContentEntityInterface $entity) : void {
  if ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'news_article') {
    $variables['has_sidebar_second'] = TRUE;
  }
}

/**
 * Implements hook_theme().
 */
function helfi_node_news_article_theme() : array {
  return [
    'news_article_hero_block' => [
      'variables' => [
        'design' => NULL,
        'title' => NULL,
        'description' => NULL,
        'image' => NULL,
        'published_time' => NULL,
        'html_published_time' => NULL,
        'updated_time' => NULL,
        'html_updated_time' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_block_access().
 */
function helfi_node_news_article_block_access(Block $block, $operation, AccountInterface $account) : AccessResultInterface {
  if ($operation === 'view' && $block->getPluginId() === 'page_title_block') {
    /** @var \Drupal\helfi_platform_config\EntityVersionMatcher $versionMatcher */
    $versionMatcher = Drupal::service('helfi_platform_config.entity_version_matcher');

    /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
    $entity = $versionMatcher->getType()['entity'];

    // Hide page title block if the node is of type news_article.
    if (
      $entity instanceof NodeInterface &&
      $entity->getType() === 'news_article'
    ) {
      return AccessResult::forbidden();
    }
  }

  return AccessResult::neutral();
}
