social_media:
  facebook_share:
    text: Facebook
    api_event: href
    api_url: 'http://www.facebook.com/share.php?u=[current-page:url]&title=[current-page:title]'
    attributes: "target|_blank\r\nclass|facebook-share"
  linkedin:
    api_event: href
    api_url: 'https://www.linkedin.com/sharing/share-offsite/?url=[current-page:url]'
    text: 'Share in Linkedin'
    attributes: "target|_blank\r\nclass|linkedin"
  twitter:
    api_event: href
    api_url: 'https://twitter.com/intent/tweet?url=[current-page:url]&status=[current-page:title]+[current-page:url]'
    text: 'Share in Twitter'
    attributes: "target|_blank\r\nclass|twitter"
  pinterest:
    api_event: href
    text: Pinterest
    attributes: "target|_blank\r\nclass|pinterest\r\nrel|noopener noreferrer"
  whatsapp:
    api_event: href
    attributes: "class|whatsapp show-for-small-only\r\ndata-action|share/whatsapp/share"
  email:
    api_event: href
    text: E-Mail
  print:
    text: Drucken
  facebook_msg:
    attributes: "target|_blank\r\nclass|facebook-msg\r\nrel|noopener noreferrer"
