<?php

declare(strict_types=1);

namespace Drupal\Tests\helfi_etusivu\Kernel;

use Drupal\helfi_api_base\Environment\EnvironmentEnum;
use Drupal\helfi_api_base\Environment\EnvironmentResolverInterface;
use Drupal\helfi_api_base\Environment\Project;
use Drupal\Tests\helfi_api_base\Traits\EnvironmentResolverTrait;
use Drupal\Tests\helfi_platform_config\Kernel\KernelTestBase;
use Elastic\Elasticsearch\Client;
use Elastic\Elasticsearch\Response\Elasticsearch;

/**
 * Base class for tests that use etusivu elastic server.
 */
abstract class EtusivuElasticTestBase extends KernelTestBase {

  use EnvironmentResolverTrait;

  /**
   * Autogenerated test index name.
   */
  protected string $indexName;

  /**
   * {@inheritdoc}
   */
  protected function setUp(): void {
    $this->indexName = 'test_' . strtolower(str_replace('\\', '_', self::class));

    parent::setUp();

    $this->setActiveProject(Project::ETUSIVU, EnvironmentEnum::Local);

    $params = ['index' => $this->indexName];
    if ($definition = $this->getIndexDefinition()) {
      $params['body'] = $definition;
    }
    $this->getElasticClient()
      ->indices()
      ->create($params);
  }

  /**
   * Index settings and mappings for the test index.
   *
   * Override to create the index with explicit mappings/settings (e.g. to
   * reproduce the analyzers a production index relies on). Returns an empty
   * array by default, which lets Elasticsearch map fields dynamically.
   *
   * @return array<string, mixed>
   *   The body passed to indices()->create(), or an empty array.
   */
  protected function getIndexDefinition(): array {
    return [];
  }

  /**
   * {@inheritdoc}
   */
  protected function tearDown(): void {
    $response = $this->getElasticClient()
      ->indices()
      ->delete(['index' => $this->indexName]);
    assert($response instanceof Elasticsearch);

    $this->assertEquals(200, $response->getStatusCode());

    parent::tearDown();
  }

  /**
   * Gets the elastic client.
   *
   * @return \Elastic\Elasticsearch\Client
   *   The elastic client.
   */
  protected function getElasticClient() : Client {
    $this->assertEquals(EnvironmentEnum::Local, $this->container->get(EnvironmentResolverInterface::class)->getActiveEnvironment()->environment);
    return $this->container->get('helfi_platform_config.etusivu_elastic_client');
  }

  /**
   * Constructs a new Elastic item.
   *
   * @param string|null $id
   *   The document ID.
   * @param array<string, mixed> $body
   *   The document body.
   */
  protected function indexItem(
    ?string $id = NULL,
    array $body = [],
  ): void {
    $this->getElasticClient()->index([
      'index' => $this->indexName,
      'id' => $id,
      'body' => $body,
    ]);
  }

  /**
   * Makes all pending documents in the test index searchable.
   *
   * Indexed documents are not visible to searches until the index is
   * refreshed. Call this once after indexing instead of polling.
   */
  protected function refreshIndex(): void {
    $this->getElasticClient()->indices()->refresh(['index' => $this->indexName]);
  }

}
