third_party_settings:
  field_group:
    group_updating_news:
      label: 'Päivittyvä uutinen'
      format_settings:
        description: "Jätä sisältöalue tyhjäksi päivittyvän uutisen yläpuolelta, jos luot päivittyvän uutisen.<br />Lisää uusin uutispäivitys viimeiseksi. Verkkosivulla uutispäivitykset näytetään lukijalle uusimmasta vanhimpaan."
    group_automatically_recommended:
      label: 'Automaattisesti suositellut sisällöt'
      format_settings:
        description: 'Suositellut sisällöt voivat olla uutisia tai artikkeleita. Suositukset perustuvat automaattisesti valittuihin uutisluokkiin. Uutisluokat valitaan sivun sisällön perusteella, kun sivu tallennetaan.'
