third_party_settings:
  field_group:
    group_updating_news:
      label: 'Päivittyvä uutinen'
      format_settings:
        description: "Jätä sisältöalue tyhjäksi päivittyvän uutisen yläpuolelta, jos luot päivittyvän uutisen.<br />Lisää uusin uutispäivitys viimeiseksi. Järjestelmä näyttää päivitykset sivulla käänteisessä järjestyksessä."
