_core:
  default_config_hash: 3ooO-bLkru7Jl91Kb8hO7pD1divveu98PTIZQiCV3pQ
langcode: en
site_settings:
  theme_color: coat-of-arms
  default_icon: home-smoke
  koro: basic
footer_settings:
  footer_color: dark
