label: "Nyhetsarkiv"
confirm_success_body: "Du får information om nya träffar till din e-post högst en gång per dag.\nVarje meddelande innehåller en annulleringslänk via vilken du kan sluta beställningen av denna sökvakt.\nSökvakterna gäller i sex månader."
already_confirmed_body: "Du får information om nya träffar till din e-post högst en gång per dag.\nVarje meddelande innehåller en annulleringslänk via vilken du kan sluta beställningen av denna sökvakt."
