external_links:
  jobs: 'https://www.hel.fi/sv/lediga-jobb'
  events: 'https://tapahtumat.hel.fi/sv'
  decisions: 'https://paatokset.hel.fi/sv'
  contact: 'https://www.hel.fi/sv/beslutsfattande-och-forvaltning/kontakta-helsingfors-stad'
ai_register_url: 'https://www.hel.fi/sv'
